services:
  db:
    image: postgres:15-alpine
    container_name: card-management-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: card-management-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: ["sh", "-c", "echo '--- Variáveis de Ambiente no Contêiner ---' && printenv | grep DB_HOST && echo '-------------------------------------' && sleep 3600"]

volumes:
  postgres_data: